services:
  postgres:
    image: postgres:16-alpine
    container_name: pt_one_million_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
